#!/bin/bash

# Decode the event
EVENT_JSON=$(echo "eyJpZCI6IjIwOTEwODYwMjM2MzE1NDAyNTIiLCJ1c2VybmFtZSI6ImJ1bGxfZ2VuaXVzIiwidGV4dCI6ImdvdCBzb21lIGJhc2U6MHhiMjAwMDAwMDAwMDAwMDAwMDAwMDAwNGMyN2Y2NTIzMDgyZjQxZDAxIG9uIHRoZSBkaXBzLCBpIGNsb3NlZCB0aGF0IHRhYiAyIGRheXMgYWdvIGFuZCBraW5kIG9mIGZvcmdvdCB1bnRpbCB0aGUgY29pbmJhc2UgbGlzdGluZyBhbm4uXG5cbml0cyBwcm9iYWJseSB0aGUgb25seSBiYXNlIHRva2VuIGkgd291bGQgb3duIGZvciBub3dcblxuaW0gbm90IGJpZyBmYW4gb2Ygd2hhdCBiYXNlIGhhcyBiZWVuIGRvaW5nIGJ1dCBiYXNlY2F0IGlzIGRpZmZlcmVudCBiZWNhdXNlIGl0cyBhIGJldCBvbiBjb2JpZS4gYmFzZSBpcyBpbiBhIGJhZCBzcG90IHJpZ2h0IG5vdyBhbmQgcm9iaW5ob29kIGlzIGEgZGlyZWN0IHRocmVhdCB0byB0aGVpciBtYXJrZXQgc2hhcmVcblxudGhlIGFjdGlvbnMgb2YgamVzc2UgYW5kIGJyaWFuIGluIHRoZSBwYXN0IHllYXJzIGhhdmUgZWFybmVkIGJhc2UgYSByZXB1dGF0aW9uIG9mIGJlaW5nIHRoZSBub24gY29vbCBjaGFpbiB0aGF0IGZ1bWJsZWQgaXRzIGluaXRpYWwgaGVhZHN0YXJ0OlxuLSBjb2lucyBvbiBiYXNlIGFyZSBub3QgZ29pbmcgdXAsIGxvdyBjZWlsaW5ncyAoYmlnIG9uZSlcbi0gdG9uZSBkZWFmIGJlaGF2aW9yIHRvd2FyZHMgdGhlIGNvbW11bml0eVxuLSBsZWFkZXJzaGlwIHR3ZWV0cyB0aGF0IGFjdGl2ZWx5IG1hZGUgcGVvcGxlIGxvc2UgbW9uZXkgYW5kIGtpbGxlZCBwcm9zcGVjdGl2ZSBtZW1lc1xuLSBvdmVybHkgYmlnIGZvY3VzIG9uIHRoZSBzb2NpYWwgYW5nbGUgKGZhcmNhc3Rlciwgem9yYSkgYXQgdGhlIHdyb25nIHRpbWUsIG5lZ2xlY3QgdG93YXJkcyBvdGhlciBhbmdsZXMgZXNwZWNpYWxseSBtZW1lc1xuLSBiZWluZyBub3RvcmlvdXNseSBsYXRlIHRvIHRyZW5kcyAoY29pbmJhc2UgbmZ0IHdhcyBhIGJpZyBvbmUpXG4tIGNvaW5iYXNlIGl0c2VsZiBiZWluZyBub3QgdGhlIGJlc3QgcmV0YWlsIHByb2R1Y3QgYXQgYWxsXG4tIHRoZSBsaXN0IGlzIGxvbmdcblxucm9iaW5ob29kIGNoYWluIGlzIGFyb3VuZCBmb3IgbGlrZSBhIG1vbnRoIGFuZCBhIGhhbGYgYW5kIHZsYWQgaXMgZW5kb3JzaW5nIHByb2plY3RzLCBjYXNoLWNhdDpuYXRpdmUgaXMgbGlzdGVkIHNwb3QsIGFjdGl2aXR5IGlzIHVwIG9ubHksIHJoIGFwcCBoYXMgMTAwcyBvZiBtaWxsaW9ucyBvZiB1c2Vyc1xuXG5pdHMgbm90IGxvb2tpbmcgZ29vZCBidXQgb2ZjIGl0cyBuZXZlciBvdmVyIGFuZCBpdCBoYXMgYSBjaGFuY2UgYW5kIGluIG15IHZpZXcgaXRzIHNvbGVseSBiZWNhdXNlIG9mIGNvYmllXG5cbmkgdGhpbmsgbGlrZSA5NSUgb2YgdGhlIHBhdGhzIHdoZXJlIGJhc2UgZG9lcyByZWFsbHkgd2VsbCBsZWFkIHRocm91Z2ggY29iaWUgc3VjY2VlZGluZyB3aXRoIGJhc2UgYXBwIGFuZCBjb2JpZXMgZW5kb3JzZWQgY29pbiBiYXNlY2F0IGRvaW5nIHdlbGwuIGhlIGlzIG9uZSBvZiB0aGUgcGVvcGxlIHdpdGggdGhlIGhpZ2hlc3QgbW90aW9uIG9uIENULCBvbmx5IHRoZSAyNS0yNiBjbGFzcyB6b29tZXJzIG1pZ2h0IG5vdCBrbm93IGhpbSwgYnV0IHJlYWxseSBoZSBpcyB0aGUgb25seSBvbmUgaSBiZWxpZXZlIHdobvIGNhbiBwdWxsIGl0IG9mZlxuXG5pIHRoaW5rIG9ubHkgdmVyeSBmZXcgcGF0aHMgaGF2ZSBjb2JpZSBmYWlsaW5nIGFuZCBiYXNlIHN0aWxsIGJvb21pbmcuIHNvIGxvZ2ljYWxseSBiYXNlY2F0IGlzIHRoZSBrZXkgdG8gdW5sb2NrIHRoZSB3aG9sZSBlY28gYW5kIHRodXMgaXMgdGhlIGJlc3QgdG9rZW4gdG8gb3duIGZvciB0aGUgYmFzZSBhbmdsZVxuXG50aGUgbGlzdGluZyBhbm5vdW5jZW1lbnQgaXMgYSBzaWduYWwgdG8gbWUgdGhhdCBsZWFkZXJzaGlwIGlzIHdpbGxpbmcgdG8gc3VwcG9ydCB0aGlzIHdhcyBhbiBpbXBvcnRhbnQgcGFydC4gbm90aGluZyBjb2JpZSBjYW4gZG8gaWYgYnJpYW4gd29uJ3QgbGlzdC4gYnV0IHNlZW1zIGxpa2UgaXRzIGdvb2Qgb24gdGhhdCBzaWRlXG5cd2lsbCBhZGQgaWYgaXQgZ29lcyBsb3dlciIsImNyZWF0ZWRfYXQiOiJTYXQgQXVnIDIyIDA4OjUyOjEzICswMDAwIDIwMjYiLCJ1cmwiOiJodHRwczovL3guY29tL2J1bGxfZ2VuaXVzL3N0YXR1cy8yMDkxMDg2MDIzNjMxNTQwMjUyIiwibWVkaWEiOlsiaHR0cHM6Ly9wYnMudHdpbWcuY29tL21lZGlhL0hRVUcxbl9XNEFBWHZXBY5qcGciXX0" | base64 -d 2>/dev/null)

# Extract fields
TWEET_ID=$(echo "$EVENT_JSON" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p')
USERNAME=$(echo "$EVENT_JSON" | sed -n 's/.*"username":"\([^"]*\)".*/\1/p')
CREATED_AT=$(echo "$EVENT_JSON" | sed -n 's/.*"created_at":"\([^"]*\)".*/\1/p')
URL=$(echo "$EVENT_JSON" | sed -n 's/.*"url":"\([^"]*\)".*/\1/p')

echo "Tweet ID: $TWEET_ID"
echo "Username: $USERNAME"
echo "Created: $CREATED_AT"
echo "URL: $URL"
echo ""
echo "Full text (first 500 chars):"
echo "$EVENT_JSON" | sed -n 's/.*"text":"\([^"]*\)".*/\1/p' | head -c 500
echo ""
echo ""
echo "Media:"
echo "$EVENT_JSON" | sed -n 's/.*"media":\[\([^]]*\).*/\1/p'
